/*
 * IDL for basics.spec.ts
 */

valuetype Origin {
    public double x, y;
};

valuetype Size {
    public double width, height;
};

valuetype Figure {
    public unsigned long id;
};

valuetype Rectangle: Figure {
    public Origin origin;
    public Size size;
};

valuetype FigureModel {
    public sequence<Figure> data;
};

interface Client {
    short methodC(); // return type is to be able to drop 'oneway'
    oneway void setFigureModel(in FigureModel figuremodel);
};

interface Server {
    oneway void setClient(in Client client);
    oneway void methodA();
    short methodB(); // return type is to be able to drop 'oneway'
    double answer(in double a, in double b);
};

