/*
 *  corba.js Object Request Broker (ORB) and Interface Definition Language (IDL) compiler
 *  Copyright (C) 2018, 2020 Mark-André Hopf <mhopf@mark13.org>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * IDL for valuetype.spec.ts
 */

// test the '_ptr' hack

//valuetype Dummy {
//    public double fubar;
//};

native Point_ptr;
native Matrix_ptr;

module testVT {

    valuetype Point {
        public double x, y;
    };

    valuetype Size {
        public double width, height;
    };

    valuetype Matrix {
        public double a, b, c, d, e, f;
    };

    valuetype Figure {
        public unsigned long id;
        public Matrix_ptr matrix;

        Point_ptr getHandlePosition(in unsigned short handleId);
    };

    valuetype Rectangle: Figure {
        public Point origin;
        public Size size;
    };

    valuetype FigureModel {
        public sequence<Figure> data;
    };

    interface Client {
        oneway void setFigureModel(in FigureModel figuremodel);
    };

    interface Server {
        oneway void setClient(in Client client);
    };

};
