/*
 *  corba.js Object Request Broker (ORB) and Interface Definition Language (IDL) compiler
 *  Copyright (C) 2018, 2021 Mark-André Hopf <mhopf@mark13.org>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * IDL for valuetype.spec.ts
 */

// test the '_ptr' hack

native VTPoint_ptr;
native VTMatrix_ptr;

valuetype VTPoint {
    public double x, y;
};

module testVT {

    valuetype Size {
        public double width, height;
    };

    valuetype VTMatrix {
        public double a, b, c, d, e, f;
        void identity();
    };

    valuetype Figure {
        public unsigned long id;
        public VTMatrix_ptr matrix;

        VTPoint_ptr getHandlePosition(in unsigned short handleId);
    };

    valuetype Rectangle: Figure {
        public VTPoint origin;
        public Size size;
    };

    valuetype Path: Figure {
        public string d;
    };

    valuetype FigureModel {
        public sequence<Figure> data;
    };

    interface Client {
        oneway void setFigureModel(in FigureModel figuremodel);
    };

    interface Server {
        oneway void setClient(in Client client);
    };

};
