/*
 * Workflow IDL
 */

valuetype Origin {
    public double x, y;
};

valuetype Size {
    public double width, height;
};

valuetype Figure {
};

valuetype Rectangle {
    public Origin origin;
    public Size size;
};

interface Server {
    oneway void init(in string session);
    oneway void logon(in string user, in string password);
};

interface Client {
    oneway void logonRequest(in unsigned long lifetime, in string disclaimer);

    unsigned long hello();
    oneway void foo(in Rectangle r);
    Rectangle bar();

    // oneway void home(in User user);
};

/*
module toad {

    struct Figure {
    };

    struct Origin {
        double x, y;
    }

    struct Size {
        double width, height;
    };

    struct Rectangle: Figure {
        Origin origin;
        Size size;
    };

    struct FigureModel {
        sequence<Figure> data;
    }
}

module workflow {
    struct User {
        string name;
        string fullname;
        string email;
        string avatar;
      };

}

*/

