interface Peer {
    string callString(in string value);
};

interface PeerSub: Peer {
    attribute string name;
};

interface Interface {
    boolean callBoolean(in boolean value);

    octet callOctet(in octet value);

    unsigned short callUShort(in unsigned short value);
    unsigned long callUnsignedLong(in unsigned long value);
    unsigned long long callUnsignedLongLong(in unsigned long long value);

    short callShort(in short value);
    long callLong(in long value);
    long long callLongLong(in long long value);

    float callFloat(in float value);
    double callDouble(in double value);

    string callString(in string value);

    @js_mapping(type=Uint8Array) sequence<octet>
    callBlob(
        @js_mapping(type=Uint8Array) in sequence<octet> value
    );
    // TODO: sequence of integer types
    @js_mapping(type=Float32Array) sequence<float> callSeqFloat(
        @js_mapping(type=Float32Array) in sequence<float> value
    );
    @js_mapping(type=Float64Array) sequence<double>
    callSeqDouble(
        @js_mapping(type=Float64Array) in sequence<double> value
    );
    sequence<string> callSeqString(in sequence<string> value);

    void setPeer(in Peer peer);
    Peer getPeer();
    string callPeer(in string value);
};
